// Connectiqo Privacy Policy — content data
// Structure: array of sections, each with an id, title, and body blocks.
// Block shapes: { p: string } | { ul: string[] } | { h3: string }

export const PRIVACY_META = {
  documentName: 'Connectiqo Privacy Policy',
  version: '1.0',
  status: 'Final Draft (Subject to Legal Review)',
  effectiveDate: 'August 19, 2026',
  lastUpdated: 'August 19, 2026',
  owner: 'HR Nexus (Partnership Firm)',
}

export const PRIVACY_SECTIONS = [
  {
    id: 'introduction',
    title: '1. Introduction & Scope',
    body: [
      { p: 'Welcome to Connectiqo ("Connectiqo", "we", "our", or "us"), a digital platform owned and operated by HR Nexus, a partnership firm having its registered office at:' },
      { p: 'HR Nexus, 307, Adjacent to Helipad, Opposite Seva Sadan, Patanjali Yogpeeth Phase 2, Shantarshah, Bahadrabad, Haridwar, Uttarakhand – 249405, India.' },
      { p: 'Connectiqo is a creator engagement platform that enables users to discover, book, and participate in one-to-one virtual sessions with verified creators, professionals, mentors, educators, entertainers, and other service providers through secure video communication technology.' },
      { p: 'We recognize that your privacy is important. Whether you are using Connectiqo as a user seeking to connect with creators or as a creator offering services through the platform, you trust us with your personal information. We are committed to handling that information responsibly, transparently, and in accordance with applicable laws.' },
      { p: 'This Privacy Policy explains how we collect, use, process, store, disclose, protect, retain, and delete personal information when you access or use the Connectiqo mobile application, website, or any related products and services.' },
      { p: 'Our objective is to provide you with clear information about:' },
      { ul: ['what information we collect', 'why we collect it', 'how we use it', 'when we share it', 'how long we keep it', 'how we protect it', 'the choices and rights available to you regarding your personal information'] },
      { p: 'By accessing or using Connectiqo, you acknowledge that you have read and understood this Privacy Policy. Where applicable under law, your use of the Platform constitutes your consent to the collection and processing of your information as described in this Privacy Policy. Nothing in this Privacy Policy limits any rights you may have under applicable law.' },
      { h3: 'Scope of this Privacy Policy' },
      { p: 'This Privacy Policy applies to all personal information collected by Connectiqo through the mobile application, website, creator onboarding, user registration, customer support, payment and payout processes, video communication services, creator verification, promotional campaigns, marketing communications, surveys and feedback, and any other services provided under the Connectiqo brand.' },
      { p: 'This Privacy Policy applies to registered users, prospective users, creators and creator applicants, mentors, educators, professionals, influencers, celebrities, guest visitors to our website, business partners, and customer support contacts.' },
      { h3: 'Services Covered' },
      { ul: ['Account registration and profile management', 'Discovery of creators and professionals', 'Booking paid virtual sessions', 'Secure video calling services', 'Session scheduling and reminders', 'Payment processing', 'Creator payouts', 'Identity verification (KYC)', 'Customer support', 'Session recordings where both participants have expressly consented', 'Marketing communications', 'Community safety initiatives', 'Future services introduced under the Connectiqo Platform, unless governed by a separate privacy notice'] },
      { h3: 'Geographic Scope' },
      { p: 'At the time of publication of this Privacy Policy, Connectiqo primarily offers its services to individuals located in India. As Connectiqo expands internationally, additional privacy disclosures, regional notices, or supplemental policies may apply to users located outside India.' },
      { h3: 'Governing Privacy Principles' },
      { p: 'Connectiqo is committed to processing personal information in accordance with the following principles: Lawfulness, Transparency, Purpose Limitation, Data Minimization, Accuracy, Security, and Accountability.' },
      { h3: 'Relationship with Other Policies' },
      { p: 'This Privacy Policy should be read together with, and forms part of, the broader Connectiqo legal framework, including the Terms of Use, Creator Agreement, Refund & Cancellation Policy, Community Guidelines, Copyright Policy, KYC & Verification Policy, Cookie Policy, and Data Retention & Deletion Policy.' },
    ],
  },
  {
    id: 'definitions',
    title: '2. Definitions',
    body: [
      { p: 'For the purposes of this Privacy Policy, unless the context otherwise requires, the following terms shall have the meanings set out below.' },
      { h3: '"Account"' },
      { p: 'An electronic account created by an individual to access, use, or manage the Services offered through the Connectiqo Platform.' },
      { h3: '"Applicable Law"' },
      { p: 'Any law, statute, regulation, ordinance, rule, judicial decision, governmental order, or regulatory requirement applicable to Connectiqo or its users, including applicable Indian privacy, consumer protection, information technology, payment, and taxation laws, as amended from time to time.' },
      { h3: '"Business Partner"' },
      { p: 'Any third party that provides products or services to Connectiqo, including payment processors, analytics providers, cloud service providers, communication service providers, customer support platforms, verification agencies, marketing partners, or other vendors engaged to support the operation of the Platform.' },
      { h3: '"Consent"' },
      { p: 'A freely given, specific, informed, and unambiguous indication of an individual’s agreement to the collection, use, disclosure, storage, or processing of Personal Information for one or more specified purposes. For session recordings, Consent requires the explicit agreement of both participants before recording begins.' },
      { h3: '"Connectiqo"' },
      { p: '"Connectiqo", "we", "our", or "us" refers to the Connectiqo Platform owned and operated by HR Nexus, a partnership firm registered in India, together with its affiliates, successors, and authorized representatives where applicable.' },
      { h3: '"Content"' },
      { p: 'Any information, text, photographs, profile information, audio, video, graphics, logos, comments, reviews, messages, recordings, live communications, digital files, documents, or other material that is uploaded, transmitted, created, published, shared, or otherwise made available through the Platform.' },
      { h3: '"Creator"' },
      { p: 'A verified individual approved by Connectiqo to offer paid or unpaid services, consultations, mentoring, educational sessions, entertainment, professional guidance, coaching, or other virtual engagements through the Platform.' },
      { h3: '"Customer Support"' },
      { p: 'Any communication between a User or Creator and Connectiqo for assistance relating to the Platform, including communications through email, chat, support tickets, feedback forms, or future support channels.' },
      { h3: '"Device Information"' },
      { p: 'Technical information collected from devices used to access the Platform, including device identifiers, operating system, browser type, application version, IP address, language settings, network information, crash reports, diagnostic information, and similar technical data.' },
      { h3: '"KYC"' },
      { p: '"Know Your Customer" or "KYC" refers to the identity verification process conducted by Connectiqo before enabling Creator payouts or where otherwise required by applicable law. KYC may include verification of identity documents, government-issued identification, tax information, banking information, facial verification, or other information reasonably required to verify identity, prevent fraud, and comply with legal obligations.' },
      { h3: '"Personal Information"' },
      { p: 'Any information relating to an identified or identifiable natural person that is collected by Connectiqo, either directly or indirectly. Personal Information may include, without limitation:' },
      { ul: ['Full name', 'Email address', 'Mobile number', 'Profile photograph', 'Date of birth', 'Government-issued identification details', 'PAN details', 'Aadhaar details (where collected and processed in accordance with applicable law)', 'Bank account information', 'Payment-related information', 'Profile information', 'Booking history', 'Video session metadata', 'Device information', 'Location information (where permitted)', 'Communications with Connectiqo', 'Session recordings', 'Any other information capable of identifying an individual'] },
      { p: 'Personal Information does not include information that has been irreversibly anonymized or aggregated such that it can no longer reasonably identify an individual.' },
      { h3: '"Platform"' },
      { p: 'The Connectiqo mobile application, website, software, APIs, systems, infrastructure, communication services, and all related technologies owned, operated, or provided by Connectiqo.' },
      { h3: '"Recording"' },
      { p: 'A digital audio or audiovisual recording created during a video session through the Platform. Recordings are created only after the express consent of both participants through the Platform. The User who booked the session may download and retain the recording; Connectiqo may access recordings for quality assurance, customer support, fraud prevention, dispute resolution, platform security, legal compliance, or other legitimate operational purposes described in this Privacy Policy; Connectiqo does not claim ownership of the intellectual property rights in the recording solely by virtue of facilitating its creation.' },
      { h3: '"Services"' },
      { p: 'The products, features, applications, websites, creator marketplace, communication tools, payment services, scheduling services, customer support, and all related functionality provided by Connectiqo.' },
      { h3: '"Session"' },
      { p: 'A scheduled virtual interaction conducted through the Platform between a User and a Creator, including video calls, audio calls, consultations, mentoring sessions, coaching sessions, educational sessions, entertainment engagements, or similar interactions.' },
      { h3: '"Third-Party Service Provider"' },
      { p: 'An independent organization engaged by Connectiqo to provide services supporting the Platform, including payment processing, cloud hosting, analytics, identity verification, customer support, messaging, communications, or infrastructure.' },
      { h3: '"User"' },
      { p: 'Any individual who accesses, browses, registers for, or uses the Platform, including individuals who book sessions with Creators. Where the context requires, "User" may include prospective users and visitors to the Platform.' },
      { h3: '"User Content"' },
      { p: 'Any Content submitted, uploaded, transmitted, created, or shared by a User or Creator through the Platform, including messages, profile information, reviews, recordings, feedback, and communications.' },
      { h3: '"Website"' },
      { p: 'The official Connectiqo website located at https://connectiqo.com, together with any future domains or subdomains owned and operated by Connectiqo.' },
    ],
  },
  {
    id: 'information-we-collect',
    title: '3. Information We Collect',
    body: [
      { p: 'Connectiqo collects information necessary to provide, operate, improve, secure, and comply with legal obligations relating to the Platform. The type of information collected depends on how you interact with Connectiqo, including whether you register as a User, apply to become a Creator, book sessions, receive payouts, communicate with customer support, or otherwise use our Services.' },
      { p: 'We may collect information directly from you, automatically through your use of the Platform, from third-party service providers, and from publicly available sources where permitted by applicable law.' },
      { h3: 'Information You Provide Directly' },
      { p: 'Account Information:' },
      { ul: ['Full name', 'Username', 'Profile photograph', 'Email address', 'Mobile number', 'Password (stored using secure cryptographic methods; Connectiqo does not store passwords in plain text)', 'Date of birth', 'Gender (optional)', 'Language preference', 'Country and state'] },
      { p: 'Profile Information (optional, added by you):' },
      { ul: ['Biography', 'Professional title', 'Areas of expertise', 'Social media links', 'Personal website', 'Education', 'Skills', 'Interests', 'Categories', 'Profile banner', 'Availability', 'Other information voluntarily added to your profile'] },
      { p: 'You may update or remove this information at any time, subject to technical limitations and legal retention obligations.' },
      { h3: 'Creator Registration Information' },
      { p: 'Individuals applying to become Creators may be required to provide: legal name, creator name, professional category, profile description, languages spoken, pricing information, availability schedule, experience, qualifications, professional certifications, social media profiles, portfolio information, creator profile photographs, promotional images/videos, and other information necessary to evaluate or maintain a Creator account. Submission of Creator information does not guarantee approval; Connectiqo reserves the right to verify, approve, reject, suspend, or remove Creator applications.' },
      { h3: 'Identity Verification (KYC)' },
      { p: 'To comply with legal obligations, prevent fraud, and facilitate Creator payouts, Connectiqo may require Creators to complete identity verification. KYC information may include: PAN Card, Aadhaar Card (where collected and processed in accordance with applicable law), government-issued identification documents, selfie verification, facial verification, address verification, bank account verification, tax information, date of birth, signature, and other documentation reasonably required to verify identity. KYC information is collected solely for verification, compliance, fraud prevention, security, and payment-related purposes.' },
      { h3: 'Payment Information' },
      { p: 'Users: billing information, payment method, transaction identifiers, payment confirmation, refund information, order history.' },
      { p: 'Creators: bank account details, account holder name, IFSC code, branch information, UPI information (if supported), tax information, payout history, settlement information.' },
      { p: 'For security reasons, Connectiqo does not store complete debit card, credit card, or payment instrument credentials on its own servers. Such information is processed by authorized payment providers, including Razorpay, in accordance with their own privacy policies and applicable laws.' },
      { h3: 'Session Information' },
      { p: 'When you book or participate in a Session: Session ID, Booking ID, Creator ID, User ID, session date, scheduled time, duration, session status, cancellation information, reschedule history, technical diagnostics, call quality metrics, network information, and device compatibility information.' },
      { h3: 'Session Recordings' },
      { p: 'Connectiqo supports recording of certain Sessions. Recording is permitted only after explicit consent has been obtained from both participants through the Platform. Where recording occurs, Connectiqo may process audio, video, voice, shared content, recording metadata, recording duration, timestamp, and recording identifiers.' },
      { p: 'Only the User who booked the Session may download and retain the recording through the Platform. Creators do not receive an automatic right to download Session recordings unless Connectiqo introduces such functionality in the future. Connectiqo may access recordings for quality assurance, customer support, dispute resolution, fraud prevention, platform security, safety investigations, legal compliance, and service improvement. Recordings are not used for advertising purposes without obtaining any additional consent required by applicable law.' },
      { h3: 'Communications' },
      { p: 'We may collect information contained in communications with Connectiqo, including customer support requests, feedback, emails, contact forms, chat messages with support, survey responses, complaint submissions, safety reports, copyright complaints, and community reports. These communications may be retained for quality assurance, training, legal compliance, and dispute resolution.' },
      { h3: 'Information from Promotions and Surveys' },
      { p: 'If you participate in contests, promotions, beta programs, or surveys, we may collect responses, opinions, preferences, prize eligibility information, marketing preferences, and event participation information. Participation is voluntary.' },
      { h3: 'Public Information' },
      { p: 'Where permitted by applicable law, Connectiqo may collect publicly available information relating to Creators for verification and profile enhancement purposes, including publicly accessible professional profiles, websites, or social media accounts.' },
      { h3: 'Information You Choose Not to Provide' },
      { p: 'Certain information requested by Connectiqo is optional. However, if you choose not to provide information necessary for a particular feature, you may be unable to access it. For example: without an email address or mobile number, you may be unable to create an account; without completing KYC verification, a Creator may be unable to receive payouts; without payment information, Users may be unable to book paid Sessions; without necessary permissions, features such as video calling or notifications may not function properly.' },
    ],
  },
  {
    id: 'automatic-collection',
    title: '4. Information We Collect Automatically',
    body: [
      { p: 'When you access or use the Connectiqo Platform, certain technical and usage information is collected automatically to enable the operation, security, maintenance, and improvement of our Services. Some information is collected directly by Connectiqo, while other information may be collected on our behalf by trusted third-party service providers integrated into the Platform.' },
      { h3: 'Device Information' },
      { ul: ['Device manufacturer, model, and type', 'Operating system and version', 'Application version', 'Screen resolution', 'Device language and time zone', 'Browser type (website)', 'Mobile carrier and network type', 'Device identifiers', 'Advertising identifiers where permitted', 'Push notification token', 'Hardware and device performance information'] },
      { h3: 'Log Information' },
      { ul: ['IP address', 'Login and logout time', 'Session duration', 'Device identifier and browser information', 'Access timestamps and requested pages', 'API requests and error logs', 'Authentication and security events', 'Network diagnostics and performance metrics'] },
      { h3: 'Usage Information' },
      { ul: ['Features accessed and pages viewed', 'Buttons clicked and search activity', 'Creator profiles viewed and categories browsed', 'Booking activity and session history', 'Time spent using features and navigation paths', 'User preferences and app engagement statistics'] },
      { h3: 'Video Session Technical Data' },
      { p: 'To facilitate secure and reliable video communication, Connectiqo and its video communication provider may process: session identifiers, call duration, join/leave time, network latency, packet loss, device performance, video resolution, audio quality, internet connection quality, bandwidth usage, error diagnostics, and session quality metrics. Connectiqo does not collect this information to monitor private conversations — it is processed to establish, maintain, troubleshoot, secure, and improve video communication services.' },
      { h3: 'Cookies and Similar Technologies' },
      { p: 'When you access the Connectiqo website or certain web-based services, we may use cookies, local storage, session storage, pixel tags, web beacons, SDK identifiers, and similar technologies to remember preferences, maintain login sessions, improve functionality, analyze traffic, measure performance, prevent fraud, and enhance security. Our use of cookies is described further in the Connectiqo Cookie Policy.' },
      { h3: 'Analytics Technologies' },
      { p: 'Connectiqo uses analytics tools including Google Analytics, Firebase Analytics, Google Search Console, and Supabase Analytics (where applicable) to understand Platform usage. These services may collect screen views, user interactions, app launches, crash frequency, retention metrics, user engagement, device information, geographic region, referring sources, and website performance statistics. Analytics data is generally used in aggregated or pseudonymized form.' },
      { h3: 'Crash Reports and Diagnostics' },
      { p: 'To improve platform stability, Connectiqo may automatically collect crash reports, stack traces, memory/CPU usage, device state, battery status, application errors, software exceptions, and performance bottlenecks.' },
      { h3: 'Push Notification Tokens' },
      { p: 'If you enable push notifications, your device may generate a notification token used to send notifications relating to booking confirmations, session reminders, creator updates, payment notifications, security alerts, account activity, product announcements, and promotional communications (where permitted). You may disable push notifications through your device settings at any time.' },
      { h3: 'Location Information' },
      { p: 'Connectiqo may collect limited location information (country, state, city, approximate location derived from IP address, time zone) where you grant permission, it is required for functionality, or collection is otherwise permitted by law. Connectiqo does not currently require continuous background GPS access for core Services.' },
      { h3: 'Security Monitoring' },
      { p: 'To protect users and the integrity of the Platform, Connectiqo may automatically monitor failed login attempts, suspicious account activity, unauthorized access attempts, multiple device logins, fraud indicators, spam detection, bot detection, abnormal transaction patterns, and account compromise indicators.' },
      { h3: 'Information from Third-Party Integrations' },
      { p: 'Where you interact with third-party services through the Platform, Connectiqo may receive technical information from those providers, including payment confirmation from Razorpay, video session status from VideoSDK, authentication information, analytics reports, cloud infrastructure metrics, security alerts, and identity verification results.' },
      { h3: 'Do Not Track Signals' },
      { p: 'Because there is currently no universally accepted standard governing "Do Not Track" (DNT) signals, Connectiqo does not respond differently to such signals at this time. If industry standards or applicable laws change, Connectiqo may update its practices accordingly.' },
    ],
  },
  {
    id: 'how-we-use',
    title: '5. How We Use Your Information',
    body: [
      { p: 'Connectiqo processes Personal Information only for legitimate business purposes necessary to provide, maintain, improve, secure, and operate the Platform. The specific purposes depend upon your relationship with Connectiqo, the features you use, your account settings, your permissions, and applicable legal requirements.' },
      { h3: 'To Create and Manage Your Account' },
      { p: 'Registering your account, verifying your email/mobile number, authenticating your identity, enabling secure login, maintaining your profile, recovering lost accounts, resetting passwords, preventing duplicate accounts, and providing customer support.' },
      { h3: 'To Provide Connectiqo Services' },
      { p: 'Discovering Creators, viewing profiles, booking Sessions, managing appointments, sending reminders, conducting video sessions, recording sessions (with consent), processing cancellations, managing reschedules, and maintaining booking history.' },
      { h3: 'Creator Verification (KYC)' },
      { p: 'Verifying identity, preventing impersonation, detecting fraudulent accounts, completing KYC requirements, verifying identification and bank ownership, confirming payout eligibility, and complying with legal/financial obligations.' },
      { h3: 'Payment Processing and Creator Payouts' },
      { p: 'Processing payments, confirming transactions, generating receipts, processing refunds, calculating Creator earnings and payouts, maintaining transaction history, preventing payment fraud, resolving disputes, and complying with financial reporting obligations. Payments are processed through Razorpay in accordance with its own privacy policy.' },
      { h3: 'Video Calling Services' },
      { p: 'Creating and authenticating video sessions, maintaining call quality, synchronizing audio/video, troubleshooting, detecting connectivity problems, preventing unauthorized access, and improving communication quality, facilitated using VideoSDK.' },
      { h3: 'Session Recordings' },
      { p: 'Where both participants consent, recordings may be processed to deliver the recording to the booking User, investigate complaints, resolve disputes, verify reported misconduct, conduct quality assurance, prevent fraud, and comply with legal obligations. Recordings are not used for advertising, promotional campaigns, or public distribution without additional required consent.' },
      { h3: 'Platform Safety and Security' },
      { p: 'Detecting fraud and identity theft, identifying fake Creator accounts, detecting spam and abuse, investigating harassment, preventing unauthorized access, monitoring security, enforcing Community Guidelines, and protecting Users from scams.' },
      { h3: 'Customer Support' },
      { p: 'Responding to requests, resolving technical issues, investigating complaints, verifying account ownership, improving service, responding to legal requests, and maintaining support records.' },
      { h3: 'Platform Improvement' },
      { p: 'Improving speed, reducing crashes, enhancing video quality, improving search and booking workflows, developing new features, improving accessibility, and testing new services.' },
      { h3: 'Analytics and Business Intelligence' },
      { p: 'Measuring engagement, improving navigation, understanding feature popularity, identifying issues, optimizing discovery and booking completion, improving retention, evaluating new features, and measuring marketing effectiveness.' },
      { h3: 'Communications' },
      { p: 'Account verification, password resets, booking confirmations, session reminders, payment confirmations, refund updates, security alerts, product announcements, service updates, customer support, policy changes, and legal notices — generally necessary for providing the Services.' },
      { h3: 'Marketing Communications' },
      { p: 'Subject to your preferences and applicable law, Connectiqo may send promotional emails, product updates, feature announcements, creator recommendations, special offers, event invitations, surveys, newsletters, and push notifications. Where required by law, consent will be obtained first. You may opt out at any time.' },
      { h3: 'Legal Compliance, Business Operations & Research' },
      { p: 'Personal Information may also be processed to comply with applicable laws and lawful requests, meet tax/accounting obligations, protect legal rights, conduct internal audits and risk assessments, and — in aggregated or de-identified form — support research, product development, and statistical analysis.' },
      { h3: 'Artificial Intelligence and Future Technologies' },
      { p: 'As Connectiqo evolves, it may introduce AI-powered features to improve user experience, platform safety, customer support, Creator discovery, scheduling, or moderation. Where required by law, Connectiqo will obtain additional consent before using Personal Information for materially different new purposes.' },
      { h3: 'Purpose Limitation' },
      { p: 'Connectiqo will not process Personal Information for purposes materially incompatible with those described in this Privacy Policy without first providing appropriate notice and, where required, obtaining your consent.' },
    ],
  },
  {
    id: 'legal-bases',
    title: '6. Legal Bases for Processing Personal Information',
    body: [
      { p: 'Connectiqo processes Personal Information only where it has a lawful basis to do so under applicable law. Depending on the nature of your interaction with the Platform, Connectiqo may rely on one or more of the following bases.' },
      { h3: 'Consent' },
      { p: 'Examples: creating an account, granting camera/microphone permission, allowing push notifications, agreeing to Session recording, receiving promotional communications, participating in surveys, uploading profile photographs, providing optional profile information. You may withdraw consent at any time where permitted by law; withdrawal does not affect the lawfulness of prior processing, but certain Services may become unavailable.' },
      { h3: 'Performance of a Contract' },
      { p: 'Creating and maintaining Accounts, processing bookings, connecting Users with Creators, scheduling Sessions, conducting video calls, processing payments and payouts, maintaining booking history, and providing customer support.' },
      { h3: 'Compliance with Legal Obligations' },
      { p: 'Identity verification, tax reporting, financial recordkeeping, fraud investigations, anti-money laundering requirements where applicable, responding to lawful governmental requests, and enforcement of legal rights.' },
      { h3: 'Legitimate Business Interests' },
      { p: 'Operating the Platform, improving service quality, preventing fraud and abuse, platform and network security, product development, analytics, customer support, internal administration, business continuity, and risk management — balanced against the privacy rights of affected individuals.' },
      { h3: 'Protection of Users, Public Interest, and Safety' },
      { p: 'Protecting Users, Creators, and minors; preventing scams, impersonation, harassment, cyber abuse, and payment fraud; protecting intellectual property and platform integrity; and, where permitted, responding to public safety concerns or assisting law enforcement.' },
      { h3: 'Data Minimization, Purpose Limitation & Accuracy' },
      { p: 'Connectiqo follows the principle of data minimization: information collected is limited to what is reasonably necessary, is not collected merely because it might become useful, and optional information is distinguished from mandatory information wherever practicable. Users and Creators are responsible for keeping their information accurate and up to date.' },
      { h3: 'Automated Decision-Making' },
      { p: 'As of the Effective Date, Connectiqo does not make decisions that produce legal or similarly significant effects solely through fully automated processing. If this changes, additional information about the logic, consequences, and applicable rights will be provided.' },
      { h3: 'Special Categories of Information' },
      { p: 'Connectiqo does not intentionally collect or process sensitive categories of Personal Information except where required for identity verification, legal compliance, or the requested Services, or voluntarily provided by the individual — in which case enhanced safeguards apply.' },
    ],
  },
  {
    id: 'sharing',
    title: '7. How and When We Share Personal Information',
    body: [
      { p: 'Connectiqo recognizes that your Personal Information belongs to you. We do not sell your Personal Information to third parties for monetary consideration. We disclose Personal Information only where necessary to operate the Platform, provide requested Services, comply with legal obligations, protect users, or pursue legitimate business purposes consistent with this Privacy Policy.' },
      { h3: 'Service Providers' },
      { p: 'Depending on the Services you use, we may share information with providers offering cloud hosting and infrastructure, video communication, payment processing, analytics, customer support, authentication, email/push delivery, security monitoring, identity verification, database hosting, backups, performance monitoring, fraud detection, and business communication tools. These providers may process Personal Information only to perform services for Connectiqo, subject to contractual and legal obligations.' },
      { h3: 'Payment Service Providers' },
      { p: 'Connectiqo uses Razorpay for payment processing. Depending on the transaction, Razorpay may process customer name, billing information, payment amount, transaction identifier, order reference, refund/payout information, bank account details (for Creator settlements), and payment status, in accordance with Razorpay’s own privacy policy. Connectiqo does not receive or store complete debit/credit card credentials.' },
      { h3: 'Video Communication Provider' },
      { p: 'Connectiqo provides one-to-one virtual Sessions using VideoSDK, which may process session identifiers, participant identifiers, connection metadata, device information, network diagnostics, session duration, technical logs, and call quality metrics solely to provide secure communication services.' },
      { h3: 'Identity Verification, Analytics, and Cloud Providers' },
      { p: 'Where required for Creator onboarding or legal compliance, identity verification providers may receive only the information necessary to perform verification. Analytics providers (Google Analytics, Firebase Analytics, Google Search Console, Supabase) may receive technical information such as device information, application events, session statistics, performance metrics, crash reports, and approximate geographic region, generally in aggregated or pseudonymized form. Cloud infrastructure providers process information necessary to host databases, store files, operate servers, maintain backups, and protect against data loss, only in accordance with Connectiqo’s instructions.' },
      { h3: 'Legal and Regulatory Disclosures' },
      { p: 'Connectiqo may disclose Personal Information where required to comply with applicable law, valid legal process, judicial orders, or lawful requests from government authorities; to protect public safety; to prevent or investigate fraud and criminal activity; and to protect Connectiqo’s legal rights. Where legally permitted and practicable, Connectiqo may notify affected individuals before disclosure.' },
      { h3: 'Business Transfers' },
      { p: 'In the event of a merger, acquisition, corporate restructuring, sale of assets, financing transaction, investment, reorganization, insolvency, or similar transaction, Personal Information may be transferred to the acquiring or successor entity, subject to applicable law and appropriate notice.' },
      { h3: 'Professional Advisors, Affiliates, and With Your Direction' },
      { p: 'Connectiqo may disclose Personal Information to legal counsel, accountants, auditors, tax consultants, compliance advisors, and insurance providers where reasonably necessary, subject to confidentiality obligations; to future corporate affiliates for lawful business operations; and to third parties where you expressly instruct or authorize us to do so (e.g. connecting external accounts, exporting information, participating in partner programs).' },
      { h3: 'Aggregated Information & No Sale' },
      { p: 'Connectiqo may use and disclose aggregated or de-identified information (which cannot reasonably identify an individual) for research, analytics, business intelligence, and product development. Connectiqo does not sell Personal Information to third parties for monetary consideration, and does not permit third parties to use your Personal Information for their own independent marketing purposes except with your express authorization or as otherwise permitted by law.' },
      { h3: 'International Expansion' },
      { p: 'At the Effective Date, Connectiqo primarily provides Services within India. If Connectiqo expands internationally and transfers Personal Information outside India, such transfers will be carried out in accordance with applicable laws and appropriate safeguards, with additional notices provided where required.' },
    ],
  },
  {
    id: 'security',
    title: '8. Data Security and Information Protection',
    body: [
      { p: 'Protecting the confidentiality, integrity, and availability of Personal Information is fundamental to Connectiqo’s operations. We maintain administrative, technical, physical, and organizational safeguards designed to protect Personal Information against unauthorized access, disclosure, alteration, destruction, misuse, accidental loss, or unlawful processing. While no security system can guarantee absolute protection, Connectiqo is committed to implementing reasonable and appropriate safeguards proportionate to the sensitivity of the information we process.' },
      { h3: 'Security Program' },
      { p: 'Where appropriate, our program includes information security policies, secure software development practices, risk assessments, access management, identity verification procedures, security monitoring, vulnerability management, incident response procedures, business continuity and disaster recovery planning, vendor security assessments, and employee security awareness.' },
      { h3: 'Encryption & Authentication' },
      { p: 'Where appropriate, Connectiqo uses industry-recognized encryption for data in transit (TLS or successor protocols) and, where technically and operationally appropriate, for sensitive data at rest, along with secure cryptographic storage of authentication credentials and secure key management. Account security measures include secure authentication, password hashing, session management, login verification, account recovery processes, and protection against automated credential attacks. Users remain responsible for keeping login credentials confidential.' },
      { h3: 'Access Controls' },
      { p: 'Access to Personal Information is restricted to authorized personnel who require it for legitimate job responsibilities, using role-based permissions, least-privilege principles, multi-factor authentication for administrative systems where appropriate, internal approval procedures, access logging, and periodic reviews.' },
      { h3: 'Protection of KYC Information and Session Recordings' },
      { p: 'Creator identity verification information is subject to enhanced safeguards including restricted internal access, secure storage, encrypted transmission, verification workflows, audit logging, and limited retention periods. Session recordings are protected from unauthorized access, disclosure, alteration, or misuse; only the booking User may download a recording through the Platform, and Connectiqo personnel access is restricted to those with a legitimate business need.' },
      { h3: 'Infrastructure, Application Security & Monitoring' },
      { p: 'Technical safeguards may include firewalls, secure network segmentation, intrusion detection, rate limiting, traffic filtering, DDoS mitigation, and continuous monitoring. Secure development practices may include code reviews, security testing, dependency management, vulnerability scanning, and secure release procedures. Connectiqo may monitor suspicious login activity, unauthorized access attempts, fraud indicators, and other security-related events solely for legitimate security and compliance purposes.' },
      { h3: 'Security Incident Response' },
      { p: 'Connectiqo maintains procedures to identify, investigate, manage, and respond to suspected or confirmed security incidents, which may include investigating affected systems, containing unauthorized activity, restoring functionality, notifying affected users and regulators where legally required, cooperating with law enforcement, and implementing corrective measures.' },
      { h3: 'Employee Confidentiality & Third-Party Security' },
      { p: 'Employees, contractors, and authorized representatives who process Personal Information are required to maintain confidentiality and comply with internal security policies. Connectiqo carefully selects service providers but each remains responsible for the security of its own systems.' },
      { h3: 'User Responsibilities & Limitation of Security Guarantees' },
      { p: 'Security is a shared responsibility — users are encouraged to choose strong passwords, keep credentials confidential, verify communications claiming to be from Connectiqo, and promptly report suspected unauthorized activity. No method of electronic transmission or storage can be guaranteed completely secure, and Connectiqo cannot warrant that unauthorized access, cyberattacks, or data breaches will never occur.' },
    ],
  },
  {
    id: 'retention',
    title: '9. Data Retention',
    body: [
      { p: 'Connectiqo retains Personal Information only for as long as reasonably necessary to provide the Services, fulfill the purposes described in this Privacy Policy, comply with legal/regulatory/tax/accounting/contractual obligations, resolve disputes, enforce agreements, protect the rights and safety of Users, Creators, Connectiqo and third parties, and establish, exercise, or defend legal claims. When no longer required, information is deleted, anonymized, or securely disposed of.' },
      { p: 'Retention periods are determined by factors including the sensitivity of the information, the purpose for which it was collected, the duration of the relationship, operational and legal requirements, potential disputes, fraud prevention needs, and technical feasibility of deletion.' },
      { h3: 'By Category' },
      { ul: [
        'Account information: retained while active; certain information may be retained after closure to comply with legal obligations, prevent fraud, maintain records, resolve disputes, or enforce the Terms of Use.',
        'Creator KYC records: retained as long as reasonably necessary for legal, tax, fraud-prevention, and regulatory purposes — may persist after account closure.',
        'Payment and financial information: retained per applicable accounting, taxation, and regulatory requirements. Complete card credentials are never stored by Connectiqo.',
        'Booking and Session information: retained for customer support, dispute resolution, fraud prevention, financial reconciliation, and legal compliance.',
        'Session recordings: retained only as long as necessary to deliver the recording, resolve disputes, investigate complaints, conduct quality assurance, and comply with legal obligations, then securely deleted. Downloaded copies become the responsibility of the downloading User.',
        'Customer support records: retained for a reasonable period to resolve issues, improve service, and comply with legal obligations.',
        'Technical/security logs: retained as appropriate for security, fraud detection, and compliance — some logs may be retained longer to support investigations.',
        'Analytics information: retained as necessary to understand usage and improve the Platform, generally in aggregated or de-identified form where practicable.',
        'Marketing preferences: retained until you withdraw consent, unsubscribe, or retention is no longer necessary; limited suppression records may be kept to honor opt-outs.',
      ] },
      { h3: 'Legal Holds & Deletion Requests' },
      { p: 'Connectiqo may retain information for longer periods where reasonably necessary to comply with legal obligations, respond to regulatory requests or court orders, investigate fraud, resolve disputes, or preserve evidence for anticipated or ongoing legal proceedings. Where you request deletion, Connectiqo will evaluate the request under applicable law — certain information may continue to be retained where legally required, necessary for fraud prevention or financial reporting, or otherwise permitted by law; where deletion cannot be completed immediately, further processing may be restricted in the interim.' },
      { h3: 'Anonymization and Secure Disposal' },
      { p: 'Where appropriate, Connectiqo may irreversibly anonymize Personal Information so it can no longer identify an individual; anonymized information is no longer considered Personal Information and may be retained for research, analytics, and product development. When information reaches the end of its retention period, Connectiqo takes reasonable steps to securely delete, anonymize, or destroy it using methods appropriate to the storage medium.' },
    ],
  },
  {
    id: 'your-rights',
    title: '10. Your Privacy Rights and Choices',
    body: [
      { p: 'Connectiqo respects your privacy and is committed to providing you with reasonable control over your Personal Information. Subject to applicable law, you may exercise the rights described in this Section; certain rights may vary depending on your jurisdiction and the nature of your relationship with Connectiqo. Where legally permitted, Connectiqo may request reasonable information to verify your identity before processing a privacy request.' },
      { ul: [
        'Right to Access — request confirmation of whether Connectiqo processes your Personal Information, and details about categories, purposes, recipients, source, and retention.',
        'Right to Correct or Update — update your information through account settings, or contact Connectiqo to correct inaccurate information (supporting documentation may be required for identity/payment-related corrections).',
        'Right to Delete — request deletion, subject to legitimate retention needs (legal compliance, financial reporting, fraud prevention, dispute resolution, contractual obligations). Deletion may result in loss of access to Services or account closure.',
        'Right to Withdraw Consent — withdraw consent at any time for consent-based processing (e.g. Session recordings, marketing, optional profile info, camera/microphone permissions, push notifications); withdrawal doesn’t affect prior lawful processing, and some Services may become unavailable.',
        'Right to Object or Restrict Processing — request that Connectiqo restrict, cease, or reconsider particular processing activities, subject to applicable legal requirements.',
        'Right to Data Portability — where required by law and technically feasible, request a copy of certain information you provided, in a structured, machine-readable format.',
        'Right to Manage Marketing Communications — opt out via unsubscribe links, notification preferences, or by contacting Connectiqo; this does not affect essential service communications (booking confirmations, receipts, session reminders, security notifications, policy updates).',
        'Right to Manage Device Permissions — manage Camera, Microphone, Notifications, and Storage/Photos permissions through device settings; disabling permissions may limit related features.',
        'Right to Lodge a Complaint — contact the designated Privacy Contact/Grievance Officer, or submit a complaint to the appropriate regulatory authority under applicable law.',
      ] },
      { h3: 'Identity Verification & Authorized Representatives' },
      { p: 'Connectiqo may require reasonable verification of your identity before responding to requests, and may decline or defer a request until verification is complete. Where permitted, an authorized representative may submit a request on your behalf with appropriate documentation of their authority.' },
      { h3: 'Limitations, Response Time & DPDP Act Rights' },
      { p: 'The exercise of privacy rights may be limited where permitted or required by law (e.g. legal obligations, judicial proceedings, regulatory investigations, fraud prevention, protection of others’ rights). Connectiqo will endeavor to respond within timeframes required by applicable law or, where none applies, within a reasonable period, extending as needed for complex or high-volume requests.' },
      { p: 'Where the Digital Personal Data Protection Act, 2023 applies, individuals may have additional rights, including to obtain information about processing, request correction or erasure, withdraw consent, seek grievance redressal, and nominate another individual to exercise rights in the event of death or incapacity, where permitted by law.' },
      { p: 'Privacy-related requests may be submitted using the details in the "Contact Us" section, including your full name, the email address associated with your account, a description of the request, and any information reasonably necessary to verify your identity.' },
    ],
  },
  {
    id: 'international-transfers',
    title: '11. International Data Transfers',
    body: [
      { p: 'As of the Effective Date, Connectiqo primarily offers its Services to individuals located in the Republic of India, and Personal Information is primarily collected, processed, and stored using infrastructure located in India or through trusted service providers supporting the Platform.' },
      { h3: 'Cross-Border Processing' },
      { p: 'Certain third-party service providers may operate servers, support personnel, backup systems, or infrastructure outside India. Accordingly, limited categories of Personal Information may be processed, accessed, or stored outside India where reasonably necessary to provide the Services, maintain cloud infrastructure, process payments, facilitate video communications, perform analytics, provide customer support, maintain system security, recover from disruptions, or comply with legal obligations — performed only to the extent reasonably necessary.' },
      { h3: 'Future International Expansion & Safeguards' },
      { p: 'If Connectiqo expands beyond India, Personal Information may be transferred to countries where Connectiqo, its affiliates, or authorized providers operate, in accordance with applicable data protection laws. Safeguards may include contractual obligations, organizational security measures, technical safeguards including encryption, access controls, confidentiality obligations, vendor due diligence, and any transfer mechanisms recognized or required under applicable law.' },
      { h3: 'Compliance with Indian Law' },
      { p: 'Connectiqo intends to conduct international transfers of Personal Information in accordance with the Digital Personal Data Protection Act, 2023 and rules made thereunder, applicable sector-specific requirements, and any lawful restrictions imposed by competent governmental authorities regarding cross-border data transfers.' },
      { h3: 'International Access and Government Requests' },
      { p: 'Authorized personnel of Connectiqo or its service providers may access Personal Information from jurisdictions outside India where reasonably necessary for technical support, infrastructure maintenance, customer support, fraud investigations, cybersecurity monitoring, or legal compliance, subject to confidentiality obligations and access controls. Where Personal Information processed outside India becomes subject to lawful requests from foreign governmental authorities or courts, Connectiqo will evaluate such requests carefully and, where legally permitted, seek to limit disclosure to what is legally required.' },
    ],
  },
  {
    id: 'childrens-privacy',
    title: '12. Children’s Privacy',
    body: [
      { h3: 'Age Eligibility' },
      { p: 'Connectiqo is intended solely for individuals who are 13 years of age or older. The Platform is not directed to, designed for, or intended to be used by children under the age of 13. Both Users and Creators must be at least 13 years old to create an account, access the Services, book or conduct Sessions, receive Creator payouts, purchase services, or otherwise use the Platform. Where a User or Creator is between 13 and 18 years of age, use of features requiring contractual or financial capacity (such as payments, KYC verification, or Creator payouts) may require the involvement or consent of a parent or legal guardian, consistent with applicable Indian law. By creating an account or using the Platform, you represent and warrant that you meet this age requirement.' },
      { h3: 'No Knowing Collection of Children’s Personal Information' },
      { p: 'Connectiqo does not knowingly collect, solicit, process, or retain Personal Information from individuals under the age of 13, and does not knowingly permit children under 13 to register an account, participate as Creators, purchase Sessions, receive payments, submit KYC documentation, upload content, or otherwise use the Platform. If Connectiqo becomes aware that Personal Information has been collected from an individual under 13 in violation of this Privacy Policy, it will take reasonable steps to investigate and, where appropriate, delete the relevant information.' },
      { h3: 'Age Verification and Accounts Identified as Underage' },
      { p: 'Connectiqo may implement reasonable age-verification measures, including collection of date of birth, identity verification for Creators, KYC verification, review of government-issued identification, and additional verification where fraud is suspected. Providing false information regarding age may violate the Terms of Use and result in suspension or termination. Where Connectiqo reasonably believes an account belongs to an individual under 13, it may suspend or restrict the account, request additional verification, disable access, remove associated content, cancel pending Sessions, withhold Creator onboarding or payouts, and permanently terminate the account, without prior notice where permitted by law.' },
      { h3: 'Reporting and Parent/Guardian Inquiries' },
      { p: 'If you believe an individual under 13 is using Connectiqo, or if a parent or guardian believes a child under 13 has provided Personal Information to Connectiqo, please contact us using the details in the "Contact Us" section. Upon a verifiable request, Connectiqo will investigate and, where appropriate, restrict access to the account and delete Personal Information where legally permissible.' },
      { h3: 'Educational or Institutional Use' },
      { p: 'Unless expressly authorized under a separate written agreement, the Platform is not intended for use by schools, educational institutions, youth organizations, or other entities for activities involving individuals under 13. Until Connectiqo introduces products intended for individuals under 13 (with a published updated notice describing applicable safeguards and parental consent requirements), the Platform remains intended exclusively for individuals aged 13 and above.' },
    ],
  },
  {
    id: 'third-party-services',
    title: '13. Third-Party Services, Websites, and Integrations',
    body: [
      { p: 'To provide, operate, improve, and secure the Platform, Connectiqo relies on carefully selected third-party service providers and technology partners, who process Personal Information only to the extent reasonably necessary to perform services on Connectiqo’s behalf.' },
      { h3: 'Current Third-Party Providers' },
      { ul: [
        'Razorpay — payment processing and Creator payouts',
        'VideoSDK — video calling infrastructure',
        'Firebase — authentication, notifications, analytics, crash reporting',
        'Google Analytics — website and application analytics',
        'Google Search Console — website performance and indexing',
        'Supabase — backend database, authentication, and application services',
      ] },
      { p: 'This list is provided for transparency and may change as Connectiqo’s business evolves. The use of any particular provider does not imply endorsement of all services offered by that provider. Third-party providers operate under their own independent privacy policies and practices — Connectiqo encourages Users and Creators to review those policies, and is not responsible for the privacy practices of independent third-party organizations except to the extent required by applicable law.' },
      { h3: 'External Websites, Third-Party Content, and App Stores' },
      { p: 'The Platform may contain links to third-party websites, applications, or online services not owned or controlled by Connectiqo — use of these is governed by their own terms and privacy practices, at the user’s own discretion and risk. Creators may reference third-party products or brands during Sessions; such references do not constitute Connectiqo’s endorsement. If you download the Connectiqo application through the Apple App Store or Google Play Store, your use of those marketplaces is governed by their respective terms, and they may independently collect information relating to downloads, purchases, and usage.' },
      { h3: 'Future Integrations and Due Diligence' },
      { p: 'As Connectiqo develops additional features, the Platform may integrate with additional providers (e.g. calendar integrations, CRM tools, communication platforms, AI services, productivity tools). Where such integrations materially affect the processing of Personal Information, Connectiqo will update this Privacy Policy and provide notice where required. Before engaging providers, Connectiqo evaluates factors such as operational capability, information security practices, legal compliance, privacy commitments, reliability, and contractual protections, and periodically reviews providers as part of its vendor management process.' },
    ],
  },
  {
    id: 'cookies',
    title: '14. Cookies, Tracking Technologies, and Similar Technologies',
    body: [
      { p: 'Connectiqo uses cookies, software development kits (SDKs), pixels, local storage, and similar technologies to operate, secure, improve, and analyze the Platform — helping provide core functionality, maintain secure sessions, remember preferences, improve performance, understand usage, diagnose issues, detect fraud, and deliver communications where permitted by law.' },
      { h3: 'Cookies and Mobile SDKs' },
      { p: 'Cookies are small text files placed on your browser (Session Cookies expire when the browser closes; Persistent Cookies remain until deleted or expired). Because Connectiqo is primarily a mobile application, many functions rely on SDKs rather than browser cookies, which may collect device identifiers, OS information, application version, crash reports, usage analytics, authentication information, notification tokens, network diagnostics, and performance metrics.' },
      { h3: 'Types of Technologies Used' },
      { ul: [
        'Essential — authentication, account security, session management, fraud prevention, network security, load balancing, platform stability, error detection.',
        'Performance and Analytics — page views, application usage, session duration, feature popularity, crash frequency, navigation paths, performance metrics, service reliability.',
        'Preference — language selection, regional preferences, accessibility settings, notification and login preferences, UI customization.',
        'Security — fraud detection, suspicious-activity identification, unauthorized-access prevention, account protection, malicious-traffic identification, abuse investigation.',
      ] },
      { p: 'Depending on the Services used, Connectiqo may utilize technologies provided by Firebase, Google Analytics, Google Search Console, Supabase, Razorpay (payment-related functions), and VideoSDK (video infrastructure), each of which may use its own technical identifiers as necessary.' },
      { h3: 'Your Choices' },
      { p: 'Depending on your device, browser, and operating system, you may be able to disable or delete cookies, clear application storage, restrict advertising identifiers, disable analytics features, and manage notification/application permissions. Disabling certain technologies may reduce the functionality, performance, or availability of portions of the Platform. There is currently no universally accepted standard governing browser "Do Not Track" signals, so Connectiqo does not currently respond differently to them.' },
      { h3: 'Consent' },
      { p: 'Where required by applicable law, Connectiqo will obtain consent before placing or enabling non-essential cookies or similar tracking technologies. Essential technologies necessary for providing the Platform may continue to operate without separate consent where permitted by law. Users may withdraw previously granted consent through available settings where supported.' },
    ],
  },
  {
    id: 'changes',
    title: '15. Changes to This Privacy Policy',
    body: [
      { p: 'Connectiqo may revise, amend, supplement, or otherwise update this Privacy Policy from time to time to reflect changes in applicable law, regulatory guidance, new or modified Platform features, changes to business operations, technological developments, security enhancements, updates to data processing practices, changes in third-party service providers, or other legitimate operational, legal, or commercial requirements. We encourage Users and Creators to review this Privacy Policy periodically.' },
      { p: 'This Privacy Policy displays an "Effective Date" and, where applicable, a "Last Updated" date. Unless otherwise stated, revisions become effective on the Effective Date specified in the updated version; where required by law, Connectiqo may specify a future effective date to allow reasonable time for review.' },
      { h3: 'Material vs Non-Material Changes' },
      { p: 'Where changes materially affect the processing of Personal Information or the rights of Users and Creators, Connectiqo will provide notice through appropriate methods (in-app notifications, email to the registered address, prominent notices on the Platform, account dashboard notifications, or similar). Administrative, editorial, formatting, or other non-material changes may be implemented without separate individual notice, reflected by an updated "Last Updated" date.' },
      { p: 'Following the Effective Date of an updated Privacy Policy, continued access to or use of the Platform may constitute acknowledgement that you have been provided access to the revised Policy; where applicable law requires express consent for particular changes, Connectiqo will obtain such consent before implementing them. If you do not agree with material changes, you may discontinue use of the Platform, close your account, withdraw consent where processing is based on consent, or exercise any applicable privacy rights — though certain information may continue to be retained where required by law.' },
    ],
  },
  {
    id: 'contact',
    title: '16. Contact Information and Grievance Redressal',
    body: [
      { p: 'If you have any questions, concerns, requests, or complaints regarding this Privacy Policy or Connectiqo’s processing of Personal Information, you may contact us using the details below.' },
      { p: 'Connectiqo, operated by HR Nexus (Partnership Firm). Registered Office: 307, Adjacent to Helipad, Opposite Seva Sadan, Patanjali Yogpeeth Phase 2, Shantarshah, Bahadrabad, Haridwar, Uttarakhand – 249405, India.' },
      { p: 'Website: https://connectiqo.com' },
      { p: 'General Email: contact@connectiqo.com' },
      { h3: 'Privacy Contact and Grievance Officer' },
      { p: 'In accordance with applicable Indian law, Connectiqo has designated a Grievance Officer responsible for addressing complaints relating to privacy, Personal Information, and this Privacy Policy:' },
      { p: 'Grievance Officer: Himanshu Jaiswal' },
      { p: 'Email: grievance@connectiqo.com' },
      { p: 'Postal Address: HR Nexus (Connectiqo), 307, Adjacent to Helipad, Opposite Seva Sadan, Patanjali Yogpeeth Phase 2, Shantarshah, Bahadrabad, Haridwar, Uttarakhand – 249405, India.' },
      { h3: 'What You Can Report' },
      { p: 'You may contact Connectiqo regarding privacy-related questions; requests to access, correct, or delete Personal Information; withdrawal of consent; concerns regarding data security; suspected unauthorized account access; complaints about the handling of Personal Information; concerns regarding Session recordings; reports of identity theft, impersonation, or fraudulent Creator accounts; concerns regarding KYC processing; and any other privacy-related concern.' },
      { p: 'To help us process your request efficiently, please include your full name, the email address associated with your account, your registered mobile number (if applicable), a clear description of your request or complaint, and any supporting documents. Connectiqo will acknowledge and respond within the timeframes required by applicable law or, where none applies, within a reasonable period, and encourages individuals to contact us directly so we may investigate and resolve concerns before any formal proceedings — without limiting your right to contact a competent regulatory authority.' },
    ],
  },
  {
    id: 'governing-law',
    title: '17. Governing Law, Jurisdiction, and Dispute Resolution',
    body: [
      { p: 'This Privacy Policy, and any matters relating to the collection, processing, storage, disclosure, or protection of Personal Information by Connectiqo, shall be governed by and construed in accordance with the laws of the Republic of India, without regard to its conflict of law principles. Nothing in this Privacy Policy shall be interpreted as limiting any mandatory rights or protections available to individuals under applicable law.' },
      { p: 'Connectiqo is committed to conducting its data processing activities in accordance with applicable laws, including the Digital Personal Data Protection Act, 2023 and rules made thereunder, the Information Technology Act, 2000 where applicable, applicable consumer protection laws, and taxation and financial reporting requirements. Where a provision of this Privacy Policy conflicts with mandatory legal requirements, applicable law shall prevail to the extent of the conflict.' },
      { p: 'Connectiqo encourages Users and Creators to raise privacy-related questions or concerns directly with us before initiating formal legal proceedings, and will make reasonable efforts to investigate and resolve concerns fairly and promptly. Subject to any mandatory legal requirements to the contrary, the courts having jurisdiction over Haridwar, Uttarakhand, India, shall have exclusive jurisdiction over disputes arising out of or relating to this Privacy Policy. Nothing in this Privacy Policy prevents any individual from exercising rights under applicable data protection laws or submitting complaints to competent governmental or regulatory authorities.' },
      { p: 'This Section governs only matters relating to this Privacy Policy and the processing of Personal Information; additional legal terms relating to use of the Platform, Creator relationships, payments, intellectual property, bookings, and commercial transactions are governed by the applicable Terms of Use, Creator Agreement, or other contractual documents published by Connectiqo.' },
    ],
  },
  {
    id: 'misc',
    title: '18. Miscellaneous Legal Provisions',
    body: [
      { p: 'This Privacy Policy constitutes the complete statement of Connectiqo’s privacy practices and should be read together with the Terms of Use, Creator Agreement, Refund and Cancellation Policy, Community Guidelines, Cookie Policy, Copyright Policy, KYC and Verification Policy, and any additional legal notices published by Connectiqo. Where another agreement specifically governs a particular service or feature, that agreement shall prevail to the extent of any inconsistency relating to that service or feature.' },
      { p: 'If any provision of this Privacy Policy is held invalid, illegal, or unenforceable, it shall be modified to the minimum extent necessary to make it enforceable, or otherwise severed without affecting the remaining provisions. Failure or delay by Connectiqo in exercising any right shall not constitute a waiver, and any waiver is effective only if made expressly in writing by an authorized representative.' },
      { p: 'Connectiqo may assign or transfer its rights and obligations under this Privacy Policy to an affiliate, successor entity, purchaser of assets, or another party involved in a lawful corporate transaction, provided the successor assumes the applicable privacy obligations; Users may not assign their rights or obligations without Connectiqo’s prior written consent, except where required by law. Connectiqo shall not be responsible for delays or failures resulting from events beyond its reasonable control (force majeure), without limiting any obligations imposed by mandatory applicable law.' },
      { p: 'By using the Platform and providing your contact information, you acknowledge that Connectiqo may communicate with you electronically (email, in-app and push notifications, SMS where applicable, and website notices), which may satisfy any legal requirement that such communications be in writing, where permitted by law. This Privacy Policy is intended solely for the benefit of Connectiqo and the individual whose Personal Information is processed, and creates no rights in favor of third parties. This Privacy Policy has been prepared in English; where translations are provided for convenience, the English version prevails in the event of any inconsistency, unless otherwise required by law. Provisions intended by their nature to survive termination — including those relating to data retention, legal compliance, dispute resolution, governing law, and enforcement of legal rights — shall continue in effect after account closure.' },
    ],
  },
  {
    id: 'effective-date',
    title: '19. Effective Date, Version Control, and Final Acknowledgement',
    body: [
      { p: 'This Privacy Policy becomes effective on the Effective Date specified below and shall remain in effect until it is replaced or updated by Connectiqo.' },
      { ul: [
        'Document Name: Connectiqo Privacy Policy',
        'Version: 1.0',
        'Status: Final (Subject to Legal Review)',
        'Effective Date: August 19, 2026',
        'Last Updated: August 19, 2026',
        'Policy Owner: HR Nexus (Partnership Firm)',
        'Applicable Region: India (with provisions for future international expansion)',
        'Language: English',
      ] },
      { p: 'By creating a Connectiqo account, accessing the Platform, or using any of the Services, you acknowledge that you have had an opportunity to read this Privacy Policy, that you understand how Connectiqo processes Personal Information and your available rights and choices, that your Personal Information may be processed as described here where permitted by applicable law, and that you agree to comply with the applicable Terms of Use governing your use of the Platform. Where applicable law requires express consent for particular processing activities, Connectiqo will obtain such consent separately.' },
      { p: 'Connectiqo is committed to building a platform that respects privacy, promotes transparency, and protects Personal Information through responsible data governance, and will continue to review and improve its privacy practices as the Platform evolves. Thank you for taking the time to read the Connectiqo Privacy Policy. If you have any questions, please contact us using the details in Section 16 — Contact Information and Grievance Redressal.' },
    ],
  },
]
